import "./globals.css";
import type { Metadata } from "next";
import { Courier_Prime } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/ui/Header";

const courier = Courier_Prime({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Resume Rumble",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={courier.className}>
          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
